apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCx8DiibelOQ3H+XgFasDTqZ2SOKxCsMrXA1milWc+Z3XV2Y72dSPQUR8jqbw6ux5EAXQL2vSEVyqaCfZeCZDKTTLsWjBdUByhJot7OrB1amjIoPNFKRHVcjjlVw9NQsv1fipefc6vgbMgzx/07Lz6zxJjXr4/2zMWIRnLu5NFIUGZHxTWkRq/M6014YtuS3AbfSIhmLOAIYvfCtwDLPgobPHJpET70bL6EMWVnBPdgWpBuyYvf+VAJN3Y0n52o/OSjf6HIK/IcVY6FxPYPma86w1SwfRnN8/dpIdJZY4nq+O+t2j/vTgHuUALsd78H/51oV1PUSq+TKOYR8RkmPwO3GGtU1QP7X86c1c8b4U2C/THlKg21eSJ0l/KWX3AbJYTJr15i7M8jmFXcWCBl6zQ7p781FWNGJFYPKpB3rkUXaKFtQRKrk6zWXtqCbuxpYYa2i/cCKZ/09qiXZgirjyrK99+fV5UE3c4pUS+xtt9ygEBiHawyhMESZpiAc8nBX4XXaZvOOJDKqrY9PL/ljAeXXATd9y0kB2kFQ/lJWXF2cxZlPUHcjKVhDVCH0PYcEx3nB0exEUJ+WOmiy1n8g6zFS6mqf6o3t3R0EED5kbXa6p1jeGH6mPxzYCYa4pN0IWUZ4LQkI5kR2eAvf3xal59XBFAm5yuyzjlKXofmliMJHsujIGv+Q7sU2/PKHyVYokBTtYaSEQ==
    admin-user: AgAQZW6Zbo9g9oGy/HhetpF0rha3VA7e31VQh8RhirjfE3bCkwBx6KxisGaufeU0ttiHHjdMOeN1PCf8GzXn5synudFG/M81u/huZ3H39YN7yBAiabK6QcjBs6V/FTHE2sytoIheJ1etcqPs3TkegqTd4XbDyxMe9Oorcb2JncvAwSWuAt7dkP5mboTnKjM5miQQPnt16w4N/ii4MXdn5asrihR8vpiLtcDBaOO7GfKdVHI1vJLMK+weJTIWwTqOoguxu43CZ5/Jbpfq0RB2wuAPHINg4Z0nTxREO+52FjgEfYB7pczydYWt1hlunjeT/pOsa7kPPLbCOunsmGFo7LAdwKd4i+97xEWeazk/ZR5L6S8M14a45egQrhtboDb2iFnSkA0b1BKgFseDArwadiM3vls6g9GVTQrc3zxE961iDbObwUU734s6wmyHNu2OjsuxGF2bfBxUXPj9/NQixzvzLoSLc8mTYOyaNjuerkyW07fvhZp/9Z+4GT2H0V65thxUsWs/LtM3VfVBIFwThrxuU8q1asgwxbRqE/9SMC2Th0Zc2azVsp4duGb9eB1RJWXETCBoe3bebKM/RFIzuxty5iRwJIrsg06SoytTaS8Gb6/BVxJc0+MOkJmryzo75LgUCsqkTvm6BnYp8BNfWa2C7j1gPegIRPj2MDtuEkVNROThiHo6R2XJVQDIea393Ksl/eqVVw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

