apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgCEj0VVAV//8iAvIV64emq9LoetWSs7UZrGvEWK+MCtsBd5ltT2GnYXG0QStP923gBTrC7no5NAJxE3QbwKw//M+RoqF8E957jr2MfL4NEx+/uIhMyIR+hc06mgrjDHUJ4I9Jm6ag560thsQVNNS42pbmo+Q0W3lfnBiXQnSBkFN0xNmbKkCo/jg9crM4caZwK9iH3vViiGsIHutXfHmftVmq/a5k5DgDJHnAtSuAb5RA9MAh8wQOqfqbKFa7XTlZMc8tg3DiJGTtRn4yD40feA8n5wvkjaviS1jjUmb49K4YbQ4KNYiZrjW3xqUyKdaSRJDf6bsbSCBgB23+t3T5tRzuBH8kkTqH+DvKU0Arix1WRA+sUx750jctSIBM+qclD+nRVMgjE0U0ykunsF8ITT0i5s2qCHZSQb4aR30bbn/Bue2CgE6X+uz4FM17kVVJxjCyB/Ymp6PBOaFs/QNuxSjLWhLoURTtPsPpGzKqlHDp7+P81EuzDF+JOBykWF5rqsBC6h3JXTm6k9hgo1yqTYSv66hs8aVhgN8z37jvSwvfSNZYCPLybs7atpxUxUwlaqvyLhmwUAeD0WtgAfi1eKVnVi71U9wXOLDQBk+SGdEWp1CQvkXq9AsS1S9/r3OZ/nWK3+dIRkOPsij5P35P+04dDSDGRuhu3tQdyuiJI/p+Mx7v8E13sl+GwdDRMfASxn8JJATg==
    admins-password: AgBUS2s0DwVaXa8nFypg1pyEQqvMl3HF2N4QXWUfhe0BDiGvmdVfBK1e4iDQalxA589MA5pacqXsnzve6O/ppo2g+pNPMNYkWT0rAHnwiwQ2puHxiYsDE3tCOpjYGzxJLLiEDulG3lrPvg8TQ0vCiuOpv1SMzQ6hsQAGMLoBtJ9a/3FZTF9GxPczuGIqHU0QifMwjse0NZ8dRjef4pUrnBbyGKCVCLqyD5cm46/lpWpQxvAQg+5VmjsqEmWuwWMUR5D/FK9XQ9DerGRRhbaUukr7TFKVPw+GydNmGKTBi7Ek3+EvPTk10w/g7n+A7yOxqFTjL6m53jom8I6PKwrUSNFHbj901EyTOg5hk51p/urOqUHfv+ThbqlU/zDC6AtC3eZllUCBrL4WVCvVelSVNGF5FsBGZEHFz4GRgHwfp++38ou7f4OS9aW8Dp4bQfr5n3kdBEfjyfBIURZYhM5LtKj/8uQ3YDAhSY/nTZF0FZUzCX2AV3ciFOMmF0fuvslJpMKdpPE29gwtMxeS9gbf+j76smYY7fw1wRkpbayspuyu9AODEJknHq55RyaxwhiEmYYC1En+L+nBaFqCMgo64YmtUD2gmPs4JxULOqkx0bqfjdZpnN5Kr6zIWn5hhgdKeMYTTIqDdu0FBZSfVIS+yQzi/S8DY7Zi6eDszszSVhNusdisGu6QORXmsGKMgM1U4rftQ8IBdQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

