apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCwjiBNIAoq4cnG3hgQWFuAIWdqbbpAwDz6068EsVPMSPqM2KEbb7KXTD+An+DcVy5XOM+SSJoCNrT1Zj9+ffqmLr8ROs6JCs5V1UC1Ta1RJ9fo1QeTimOJO2SBVslc5UPwF9zN1UFww7C6c8NV9PuI4ov37ecav5mFFqEkLEWJ6Q5h+KG+34ycNORPeaN+THKBHNgCNS2MSndiWq+2it5Eo6RPujfKasXCsp3+krhoDjlZ38QCSIA8QK7uVCkc7TmbecXanM5kHKFP2XoF7f04LBB0SnuJlVzC4cZ6kEj87TY0fZLp4AemWsXP/4WIXfDjegBV0QNz9V9g5696dNE3ktBajQyXoYnSx21p4Q/wGPV07IQ+w9fQ1HnL5AqIUHo1QFdPLyE1/ARlFytvIgPnB0U3ke2irmKmy+PSaaOSlReFfsMZH+/rklhjU7qUkFs3WuGH87HDiAfKEY7VwoU4xnXqYdp10/UqDlUu7yklzTIR4DBTQKOOS4Lhh68RXiQn3KVrcsHKKOvVPbx00RsGK0UZyNwuI1SdAAqogaEhVAuWkOxWzTwLdCm3TsepaZcBIUd9BgK90gLYqRVC3U269lcD4HWfplIqIEGT3aGln2SoLGXilotpw1JeXhMn2qrRN2ttAq3Fzw3KhGO5dm4GMqAczn+OgSi6ogzZTO3HJQr/rC4y4iyiBWL/8HhKf3dWN6kIOg==
    admin-user: AgC734WocqvNAtHWRBthPddjOt5L63+fF5GiX8hrJV0h3PdnI2cJFW3MgOi3hUVIIaBZdgmzfpjNxTWlJgPmf7cPfLik8Gf73A182Q6v3iM7uUQ6slRKV08uGt4f93yKmLVT4IbmbX9PqWL+JeNcAN1zVK5gosmB6Upvuh66aXTFZXYnVsvO1l5Hu495Gc3M1iAWdEin2jygdvrLeA5Idjy2npRmmc2rijVBgTAaVeHTFOkE58u/csbxiwSIonofonbadvwEzsApxmFKpKpX1fWHhulNnyl+xBxjUEd7H2Xc4VvT7mwVATIZSwP5jv7W0kzgpcSVClIrona0r226fk/nd/ZZFIMiZqGoL/1AHRBel4vurAickPKSXYIq4QYDaMzuvhp/i6ItoNA4E9b6HfWyIqOU/A2MQfXb9ZdQMjUUwnHwrZjsRaDfnEo8ivuyKcudZEgFHM9plyqv0gd2k3q1WubmG5FFrzFGFExtrPvBVM1VY9wofT7hz3oSgjk43LLkQ5laYxko47dsewpM2JWihfGpfx7ycPfTHQDnywko8Bf6pMuRMokq/5NHS3gTzBQUDBdnTNhtC90TXHQeP6bFL21yfjAk5AREEyhxWcCfssIo1b/rpNGeFrEdFBtOByqcmn9EHkIRfbD0O3MkdAIhy5c7qMJI5bkqgtxAOSLnYbKjutlNIIDrgtrRQ9LNR9KSbZ8cvw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

