apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCKyqiMTxmmiZHfcL+DLoscHuIWcUp6RLmw9hEH1ToFajay0D03Df+qTegk46fByU8x0YxECZVxfbWJqqlF7CRI2YqWLjUWjGzxkn9UsJoWnhbv79HkbCEjmbd4whoGDk0mFg5bI2KLd+uTud92R0YbhMaJh8w0gJiyGnDM3Dgy4fF0bKked/rlKV6P8oc0dY50wQfnIWyGBWrk8eTJ5b9cwaTj8g/Z3tzUr2lc96caFshab2Yxq5hPK+fP6/XcQEN1d56cs0CN52xWKsVVeP18jfhPq1Q05aRRsyeRP9L8YmzD9ljDO5hqJ77XCgfsRiMWN7M1n/rW5MPhWHzNsAkjz6x78u+aqXJyLecGAmzHs+hw02LgReqpoH2cG11PtXbFkskWigftLHBuHJTeUZ9I9//WbZiBKF3a7IqWjw7yZTfkM7+0eXcFW0p4HILwudg0o8WOK08mv1RH1uB0a2MF1KYfGk0kYQ7Cey87XNrBl1uBR+cMeX2Fs79N6Vt7kLHvfMxfbbm5XjD9M591Vj9zrihxRno1CjZWdJ6wR0ZJlXlisK+xlHIjo+t5NiXfOa5mCRjA3T5AEOeQaA8flf8ZZyL08MRHpXoDSzmx3DIyA3MdXzzBCXC4wtyO9bWrU66wkmj+PjgjeAQMkUkIcdlT9y5MzF7xcxLCfyKXiXx7u0QSDxWhVozED9/Fbfq7dmNT1Ked2A==
    admin-user: AgA6lXSqEHx2Xh2hejNgFTLBn8I2p7MrW0pups5o90PsmUrD42lm8yBMexMRSUqmPk7Yu97b/oIHG5EWeetarukLLlKNW8xIawj37BDf7WBS4EPMuE3Ovr8tDwXiL0tA65gUV6pPK2s1eG0Z+H+3mHC89BQbgajNaq9/NjarOmHp+/au2ALUCEjuNdBWODyqWnFaIYyuInRNzWo56+X+1KousGFuXFjpFuvHuXl2SKDdcu5TA7nPgar4RqX8oZtPXT/lqEfUYpIxhUMwAOlK18xaSLKeF/0ViNo2zHUcvDiqVIYCDTPu3Jwb5kCXyBt9WSfRaRCietLKXR+wlKws9xkgigIBRHVHOm1/1MhzTMvjFj58Es7FRI5awvHLpMaQ/FqrwR7vb6ExOW+2vzayhob5kZucnJ3rPxHb8gZL8es/UIhYbCG//DRgDgi0MuEk+qFobfmX+EWeSHthXuOhBzhfZOF5VuJwWs4tV6W8RKM9GoFnXF1vDMwHYX7GfjZi0dj8Qxx7ovwER7zRV0ucV6oNLBKufsLqV5g2WZES1HBbM+9PGA2IY/taBfxhxoQ2Kn+ObyoPTFw1SWejIismJeWZ9FkZX3UcQXLSPsPU/0a/U221MaAMHNpouUmKyaod5Iw+rKxbZ0iymMKpaE03jltQBC38KITGoXKb51fTBlrBfdVyoqqCvspbfmjVX0ySfoo3wBMhxA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring

