---
# Chart: https://github.com/falcosecurity/charts/tree/master/falco
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: "12.8.0"
  values:
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: admin-user
        passwordKey: admin-password