---
# Chart: https://github.com/falcosecurity/charts/tree/master/falco
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chart:
    repository: https://grafana.github.io/helm-charts
    name: grafana
    version: "6.1.15"
  values:
    admin:
      existingSecret: "grafana-admin-credentials"
      userKey: admin-user
      passwordKey: admin-password